name: tfakkarni-app

services:
  frontend:
    container_name: tfakkarni-frontend
    build:
      context: .
      dockerfile: frontend/Dockerfile
      args:
        API_BASE_URL: http://localhost:9090
        KEYCLOAK_URL: https://lemur-12.cloud-iam.com/auth
        KEYCLOAK_CLIENT_ID: tfakkarni-frontend-docker
    image: tfakkarni/frontend:latest
    ports:
      - "18080:80"
    networks:
      - tfakkarni-network
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 256M

networks:
  tfakkarni-network:
    name: tfakkarni-network
    driver: bridge
