package org.techhive.trackingservice.entity;

import jakarta.persistence.*;
import lombok.*;
import java.time.LocalDate;
import java.time.LocalDateTime;

/**
 * Represents a daily follow-up reminder generated by the scheduler
 * when a patient's caregiver has not completed the daily follow-up log.
 */
@Entity
@Table(name = "follow_up_reminders")
@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class FollowUpReminder {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /** Keycloak ID of the patient concerned by this reminder */
    @Column(name = "patient_keycloak_id", nullable = false)
    private String patientKeycloakId;

    @Column(name = "patient_name")
    private String patientName;

    /** The date for which the follow-up was missing */
    @Column(name = "reminder_date", nullable = false)
    private LocalDate reminderDate;

    /** Human-readable message describing what is missing */
    @Column(name = "message", columnDefinition = "TEXT")
    private String message;

    /**
     * Comma-separated missing categories.
     * Possible values: NUTRITION, MEDICATION, ACTIVITY
     */
    @Column(name = "missing_categories")
    private String missingCategories;

    /** Whether the caregiver has acknowledged this reminder */
    @Column(name = "is_read", nullable = false)
    @Builder.Default
    private boolean read = false;

    @Column(name = "read_at")
    private LocalDateTime readAt;

    @Column(name = "created_at", nullable = false, updatable = false)
    private LocalDateTime createdAt;

    @PrePersist
    protected void onCreate() {
        this.createdAt = LocalDateTime.now();
    }
}
