/**
 * Reads .env and generates src/environments/environment.ts
 * Run: node scripts/set-env.js
 */
const fs = require("fs");
const path = require("path");

const envPath = path.resolve(__dirname, "..", ".env");
const outPath = path.resolve(
  __dirname,
  "..",
  "src",
  "environments",
  "environment.ts",
);

// Parse .env
const env = {};
if (fs.existsSync(envPath)) {
  const lines = fs.readFileSync(envPath, "utf-8").split("\n");
  for (const line of lines) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith("#")) continue;
    const eqIndex = trimmed.indexOf("=");
    if (eqIndex === -1) continue;
    const key = trimmed.slice(0, eqIndex).trim();
    const value = trimmed.slice(eqIndex + 1).trim();
    env[key] = value;
  }
}

const googleKey = env.GOOGLE_MAPS_API_KEY || "MISSING_KEY";

const content = `// AUTO-GENERATED by scripts/set-env.js — do not edit manually
export const environment = {
  production: false,
  googleMapsApiKey: '${googleKey}',
};
`;

fs.mkdirSync(path.dirname(outPath), { recursive: true });
fs.writeFileSync(outPath, content, "utf-8");
console.log(
  `✔ environment.ts generated (API key ${googleKey === "MISSING_KEY" ? "MISSING — update .env" : "loaded"})`,
);
