spring:
  application:
    name: analytics-service
  config:
    import: optional:configserver:${SPRING_CLOUD_CONFIG_URI:http://localhost:8888}
  data:
    redis:
      host: primary-vulture-99858.upstash.io
      port: 6379
      password: gQAAAAAAAYYSAAIncDFkOTMwMDQ3MDY3NTY0YzA1YWIwNmRjOTNiMjg4MzFlYXAxOTk4NTg
      ssl:
        enabled: true
  cache:
    type: redis
    redis:
      time-to-live: 3600000 # 1 hour
      cache-null-values: false
  cloud:
    config:
      fail-fast: true
      retry:
        initial-interval: 3000
        max-attempts: 10
        max-interval: 10000
        multiplier: 1.5
