jenkins:
  securityRealm:
    local:
      allowsSignup: false
      users:
        - id: "${DEVOPS_ADMIN_USER}"
          password: "${DEVOPS_ADMIN_PASSWORD}"
  authorizationStrategy:
    loggedInUsersCanDoAnything:
      allowAnonymousRead: false
  systemMessage: "Welcome to Tfakkarni Jenkins DevOps Server - Automated with JCasC! 🎉"
  numExecutors: 2
  crumbIssuer:
    standard:
      excludeClientIPFromCrumb: false

credentials:
  system:
    domainCredentials:
      - credentials:
          - usernamePassword:
              scope: GLOBAL
              id: "git-credentials"
              username: "${GIT_CREDENTIAL_USER}"
              password: "${GIT_CREDENTIAL_PAT}"
              description: "GitHub Credentials (PAT)"
          - usernamePassword:
              scope: GLOBAL
              id: "dockerhub-credentials"
              username: "${DOCKERHUB_USERNAME}"
              password: "${DOCKERHUB_PASSWORD}"
              description: "DockerHub Credentials"

unclassified:
  sonarGlobalConfiguration:
    buildWrapperEnabled: true
    installations:
      - name: "SonarQube"
        serverUrl: "http://sonarqube:9000"
        credentialsId: "sonar-token"
  
tool:
  maven:
    installations:
      - name: "Maven-3.9"
        properties:
          - installSource:
              installers:
                - maven:
                    id: "3.9.6"
  nodejs:
    installations:
      - name: "NodeJS-20"
        properties:
          - installSource:
              installers:
                - nodejsInstaller:
                    id: "20.12.2"

jobs:
  - script: >
      pipelineJob('Backend-Pipeline') {
          definition {
              cpsScm {
                  scm {
                      git {
                          remote {
                              url('https://github.com/TechHive-4SAE11/ESPRIT-PI-4SAE11-2026-Tfakkarni.git')
                              credentials('git-credentials')
                          }
                          branch('main')
                      }
                  }
                  scriptPath('Jenkinsfile.backend')
              }
          }
      }
      pipelineJob('Frontend-Pipeline') {
          definition {
              cpsScm {
                  scm {
                      git {
                          remote {
                              url('https://github.com/TechHive-4SAE11/ESPRIT-PI-4SAE11-2026-Tfakkarni.git')
                              credentials('git-credentials')
                          }
                          branch('main')
                      }
                  }
                  scriptPath('Jenkinsfile.frontend')
              }
          }
      }
