# ============================================================
# user-service — centralized config
# ============================================================
server:
  port: 18081

spring:
  datasource:
    url: ${NEON_DATABASE_URL:jdbc:postgresql://ep-purple-sun-aga3c9f6-pooler.c-2.eu-central-1.aws.neon.tech:5432/neondb?sslmode=require&channel_binding=require}
    username: ${NEON_USER:neondb_owner}
    password: ${NEON_PASSWORD:npg_4kKCY7bocxUn}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        auto_quote_keyword: true

keycloak:
  server-url: https://lemur-12.cloud-iam.com/auth
  realm: tfakkarni
  admin:
    username: admin
    password: "${KEYCLOAK_ADMIN_PASSWORD:3ejcJta;Mz7UE//OjV0M}"
  frontend-client-id: tfakkarni-frontend

mailtrap:
  token: f4ed6c5f383c7fe7e305eba8d1bcaef9
  inbox-id: 4413425
  from: noreply@tfakkarni.com

didit:
  api-key: ${DIDIT_API_KEY:}
  workflow-id: ${DIDIT_WORKFLOW_ID:}

---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
